GET http://localhost:5057/games/




###
POST http://localhost:5057/games
Content-Type: application/json

{   "name":"Street Fighter",
    "genreId": 4,
    "price": 50,
    "releaseDate": "2022-12-31"
}
 


###
PUT http://localhost:5057/games/8
Content-Type: application/json

{
}






###
DELETE http://localhost:5057/games/13