GET http://localhost:5057/games

###
GET http://localhost:5057/games/2

###
POST http://localhost:5057/games
Content-Type: application/json

{
    "name": "GTA 6",
    "genre": "Action",
    "price": 50,
    "releaseDate": "2022-12-31"
}

###
PUT http://localhost:5057/games/1
Content-Type: application/json

 {
    "id": 1,
    "name": "Mario Bros",
    "genre": "Platform",
    "price": 99,
    "releaseDate": "1985-09-13"
  }

  ###
DELETE http://localhost:5057/games/2
